# Generated by Django 2.2 on 2019-05-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20190507_1350'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemdopedido',
            unique_together=set(),
        ),
    ]
