# Generated by Django 2.2 on 2019-04-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_itensdopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItensDoPedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
