# Generated by Django 2.2 on 2019-04-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20190410_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar parametro NF-e'), ('permissao2', 'Essa he a permissao 2'), ('permissao3', 'Essa he a permissao 3 '))},
        ),
    ]
