# Generated by Django 2.2 on 2019-04-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20190411_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuario pode alterar parametro NF-e'), ('ver_dashboard', 'Pode visualizar o Dashboard'), ('permissao3', 'Essa he a permissao 3 '))},
        ),
    ]
