# Generated by Django 2.2 on 2019-04-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20190410_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntensPedido',
        ),
    ]
