# Generated by Django 2.2 on 2019-04-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_intenspedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntensPedido',
        ),
    ]
