# Generated by Django 2.2 on 2019-04-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20190410_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar_clientes'),)},
        ),
    ]
